### ISSUE TITLE
change the state of "selected" prop depending on number of buttons selected

### ISSUE THREAD

**Issue by kirhim** [danceyoung/react-native-selectmultiple-button#1]
Thanks so much for this awesome code. I am really loving it! I have one question though.

Is there a way I can change the state of "selected" prop, depending on number of buttons selected? 

For example, if I select more than 3 buttons, I want other buttons to be unselectable.

How would I do it?

**Comment by danceyoung** [comment]
Thanks feedback. This is a new and good feature that setting maximum number selected buttons. I will update this feature, or you can push a PR

**Comment by danceyoung** [comment]
@kirhim Hey, i have add the maximumNumberSelected prop to SelectMultipleGroupButton component, and now publish 0.1.105 version to npmjs, please try. Of cource, i have fixed some issues.
Thanks
