### ISSUE TITLE
customizing buttons with images

### ISSUE THREAD

**Issue by kirhim** [danceyoung/react-native-selectmultiple-button#2]
Hi, 

I am using your library very well and it works great. I really love it! 

I just wanna know if I could insert an image inside `<SelectMultipleButton/>` Please let me know!

Thanks in advance! :)

**Comment by danceyoung** [comment]
Now it can't. I will update the feature, thanks

**Comment by webdevsyd** [comment]
> Now it can't. I will update the feature, thanks

Is the feature now available?

**Comment by danceyoung** [comment]
@webdevsyd not available
