### ISSUE TITLE
disable Tap for defaultselectIndex

### ISSUE THREAD

**Issue by blackmamb41** [danceyoung/react-native-selectmultiple-button#6]
how can i disable Tap on defaultSelectIndex,.

so i want disable unselect on selected button

#cheers

**Comment by danceyoung** [comment]
sorry, i do not work for 7 days chinese new year. 
Now not supporting this feature, i think you should use SelectMultipleButton to manage the default selected buttons whether disable tapping by your code.

**Comment by tiffanym19** [comment]
Does this features available already?
