### ISSUE TITLE
componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by Bilal-Abdeen** [danceyoung/react-native-selectmultiple-button#8]
I got the following warning message. 
```Warning: componentWillReceiveProps has been renamed, and is not recommended for use. ```

I suggest replacing (componentWillReceiveProps), which is used in the file (\libraries\SelectMultipleButton.js), with an alternative method.

**Comment by danceyoung** [comment]
hope you pull request
